In [25]:
import pandas as pd
df=pd.read_csv('/home/miguel/msc-tesis/ssl_satellital/exp_34/logs/exp_34_train.csv')
df

,kfold,iteracion,arquitectura,val_loss,val_accu,test_loss,test_accu,test_precision,test_recall,test_f1score,support
0,0,0,ResNet152,0.395534,0.901081,0.426552,0.902513,0.904421,0.902513,0.902514,NaN
1,0,0,InceptionV3,0.352905,0.905057,0.361833,0.902831,0.904252,0.902831,0.902717,NaN
2,0,0,InceptionV4,0.945666,0.880884,0.910973,0.877067,0.887982,0.877067,0.876694,NaN
3,0,0,co-train,NaN,NaN,NaN,0.908715,0.912241,0.908715,0.908497,NaN
4,0,1,ResNet152,0.488441,0.880089,0.483777,0.887246,0.891215,0.887246,0.886980,NaN
...,...,...,...,...,...,...,...,...,...,...,...
75,3,3,co-train,NaN,NaN,NaN,0.925254,0.925821,0.925254,0.924706,NaN
76,3,4,ResNet152,0.382540,0.918575,0.421491,0.908715,0.910775,0.908715,0.908197,NaN
77,3,4,InceptionV3,0.357297,0.913486,0.365980,0.914440,0.915023,0.914440,0.913736,NaN
78,3,4,InceptionV4,1.022371,0.897583,1.143645,0.895674,0.906651,0.895674,0.895274,NaN
79,3,4,co-train,NaN,NaN,NaN,0.921120,0.923758,0.921120,0.920476,NaN

In [28]:
import numpy as np

table = pd.pivot_table(df, values=['test_accu','test_precision',
                                   'test_recall','test_f1score'], index=['arquitectura'],
                    columns=['iteracion'], aggfunc=[np.mean])

round(table*100,2)

                  mean                                                         \
             test_accu                             test_f1score
iteracion            0      1      2      3      4            0      1      2
arquitectura
InceptionV3      90.33  90.68  90.07  90.92  91.12        90.30  90.65  90.02
InceptionV4      87.00  86.15  87.12  88.03  86.87        87.01  86.16  87.07
ResNet152        90.19  90.12  89.64  90.57  90.97        90.17  90.09  89.60
co-train         91.42  91.67  91.26  91.95  91.98        91.38  91.64  91.21

                                                                       \
                           test_precision
iteracion         3      4              0      1      2      3      4
arquitectura
InceptionV3   90.87  91.05          90.46  90.79  90.20  91.00  91.24
InceptionV4   88.07  86.68          88.04  87.41  88.32  89.40  88.22
ResNet152     90.54  90.93          90.41  90.34  90.01  90.80  91.18
co-train      91.92  91.92          91.60  91.82  91.49  92.14  92.19


             test_recall
iteracion              0      1      2      3      4
arquitectura
InceptionV3        90.33  90.68  90.07  90.92  91.12
InceptionV4        87.00  86.15  87.12  88.03  86.87
ResNet152          90.19  90.12  89.64  90.57  90.97
co-train           91.42  91.67  91.26  91.95  91.98

In [29]:
import numpy as np

table = pd.pivot_table(df, values=['test_accu','test_precision',
                                   'test_recall','test_f1score'], index=['arquitectura'],
                    columns=['iteracion'], aggfunc=[np.std])

round(table*100,2)

                   std                                                         \
             test_accu                         test_f1score
iteracion            0     1     2     3     4            0     1     2     3
arquitectura
InceptionV3       0.15  0.15  0.21  0.20  0.29         0.16  0.16  0.20  0.22
InceptionV4       0.97  1.99  1.18  0.83  3.00         0.96  2.02  1.26  0.74
ResNet152         0.20  1.07  1.54  0.67  0.29         0.21  1.08  1.56  0.67
co-train          0.44  0.44  0.56  0.64  0.55         0.43  0.43  0.60  0.63

                                                                             \
                   test_precision                         test_recall
iteracion        4              0     1     2     3     4           0     1
arquitectura
InceptionV3   0.30           0.16  0.15  0.19  0.19  0.23        0.15  0.15
InceptionV4   3.31           1.02  1.94  1.14  0.46  2.89        0.97  1.99
ResNet152     0.29           0.15  0.97  1.22  0.54  0.26        0.20  1.07
co-train      0.55           0.32  0.40  0.55  0.48  0.41        0.44  0.44



iteracion        2     3     4
arquitectura
InceptionV3   0.21  0.20  0.29
InceptionV4   1.18  0.83  3.00
ResNet152     1.54  0.67  0.29
co-train      0.56  0.64  0.55

## Accuracy By Class

In [1]:
import pandas as pd

In [4]:
df_accbycls = pd.read_csv('/home/miguel/msc-tesis/ssl_satellital/exp_34/logs/exp_34_accBycls.csv')
df_accbycls.iloc[:50,:]

,kfold,iteracion,arquitectura,accBycls
0,0,0,ResNet152,[0.95 0.84 0.83 0.89 0.94 0.89 0.97 0.63 0.95 ...
1,0,0,InceptionV3,[0.72 0.66 0.77 0.71 0.91 0.85 0.96 0.51 0.91 ...
2,0,0,InceptionV4,[0.96 0.84 0.83 0.86 0.81 0.74 0.97 0.61 0.93 ...
3,0,0,co-train,[0.97 0.86 0.86 0.88 0.9 0.86 0.97 0.63 0.97 ...
4,0,1,ResNet152,[0.92 0.78 0.86 0.86 0.95 0.89 0.99 0.61 0.97 ...
5,0,1,InceptionV3,[0.79 0.72 0.84 0.76 0.91 0.89 0.96 0.52 0.94 ...
6,0,1,InceptionV4,[0.91 0.84 0.85 0.89 0.81 0.77 0.96 0.53 0.95 ...
7,0,1,co-train,[0.95 0.84 0.92 0.86 0.92 0.88 0.99 0.6 0.97 ...
8,0,2,ResNet152,[0.95 0.79 0.89 0.91 0.9 0.95 0.98 0.49 0.97 ...
9,0,2,InceptionV3,[0.8 0.79 0.9 0.79 0.92 0.87 0.98 0.5 0.93 ...
10,0,2,InceptionV4,[0.96 0.84 0.84 0.87 0.84 0.78 0.99 0.64 0.94 ...
11,0,2,co-train,[0.95 0.84 0.89 0.89 0.86 0.87 0.99 0.56 0.97 ...
12,0,3,ResNet152,[0.94 0.86 0.93 0.91 0.96 0.91 0.99 0.55 0.94 ...
13,0,3,InceptionV3,[0.79 0.78 0.94 0.86 0.9 0.91 0.97 0.45 0.94 ...
14,0,3,InceptionV4,[0.93 0.84 0.9 0.91 0.82 0.78 0.96 0.58 0.97 ...
15,0,3,co-train,[0.96 0.86 0.93 0.92 0.96 0.92 0.97 0.54 0.96 ...
16,0,4,ResNet152,[0.99 0.84 0.92 0.95 0.96 0.89 0.99 0.58 0.95 ...
17,0,4,InceptionV3,[0.93 0.82 0.96 0.89 0.95 0.88 0.99 0.54 0.96 ...
18,0,4,InceptionV4,[0.96 0.81 0.94 0.94 0.8 0.79 0.98 0.52 0.96 ...
19,0,4,co-train,[0.99 0.85 0.94 0.95 0.93 0.88 0.99 0.49 0.97 ...
20,1,0,ResNet152,[0.97 0.89 0.9 0.86 0.86 0.77 0.96 0.55 0.96 ...
21,1,0,InceptionV3,[0.8 0.73 0.74 0.79 0.89 0.84 0.96 0.53 0.91 ...
22,1,0,InceptionV4,[0.95 0.83 0.87 0.9 0.81 0.78 0.95 0.63 0.94 ...
23,1,0,co-train,[0.96 0.89 0.89 0.88 0.86 0.86 0.96 0.62 0.96 ...
24,1,1,ResNet152,[0.94 0.85 0.85 0.89 0.92 0.91 0.96 0.63 0.97 ...
25,1,1,InceptionV3,[0.8 0.76 0.81 0.76 0.89 0.9 0.97 0.51 0.92 ...
26,1,1,InceptionV4,[0.94 0.83 0.84 0.9 0.81 0.83 0.95 0.59 0.93 ...
27,1,1,co-train,[0.95 0.85 0.87 0.91 0.93 0.91 0.96 0.64 0.97 ...
28,1,2,ResNet152,[0.96 0.89 0.84 0.85 0.96 0.87 0.96 0.56 0.97 ...
29,1,2,InceptionV3,[0.84 0.77 0.84 0.79 0.89 0.89 0.96 0.54 0.95 ...
30,1,2,InceptionV4,[0.95 0.83 0.86 0.87 0.81 0.79 0.95 0.61 0.95 ...
31,1,2,co-train,[0.96 0.84 0.89 0.86 0.94 0.91 0.96 0.57 0.97 ...
32,1,3,ResNet152,[0.95 0.82 0.89 0.86 0.98 0.87 0.97 0.6 0.96 ...
33,1,3,InceptionV3,[0.83 0.79 0.95 0.79 0.94 0.9 0.95 0.48 0.96 ...
34,1,3,InceptionV4,[0.96 0.88 0.92 0.86 0.8 0.74 0.95 0.62 0.94 ...
35,1,3,co-train,[0.96 0.86 0.92 0.84 0.94 0.84 0.96 0.64 0.96 ...
36,1,4,ResNet152,[0.94 0.85 0.91 0.93 0.98 0.86 0.99 0.54 0.98 ...
37,1,4,InceptionV3,[0.94 0.75 0.94 0.87 0.93 0.85 0.97 0.51 0.95 ...
38,1,4,InceptionV4,[0.96 0.81 0.94 0.92 0.79 0.76 0.97 0.66 0.97 ...
39,1,4,co-train,[0.96 0.84 0.95 0.93 0.94 0.91 0.98 0.59 0.96 ...
40,2,0,ResNet152,[0.96 0.89 0.91 0.84 0.96 0.92 0.97 0.56 0.96 ...
41,2,0,InceptionV3,[0.8 0.71 0.76 0.78 0.86 0.82 0.96 0.52 0.9 ...
42,2,0,InceptionV4,[0.95 0.84 0.87 0.89 0.81 0.77 0.95 0.64 0.94 ...
43,2,0,co-train,[0.96 0.89 0.9 0.87 0.94 0.91 0.96 0.63 0.96 ...
44,2,1,ResNet152,[0.96 0.81 0.84 0.86 0.93 0.91 0.96 0.51 0.94 ...
45,2,1,InceptionV3,[0.79 0.76 0.8 0.71 0.93 0.88 0.96 0.51 0.94 ...
46,2,1,InceptionV4,[0.96 0.8 0.87 0.88 0.79 0.84 0.95 0.65 0.95 ...
47,2,1,co-train,[0.96 0.81 0.86 0.86 0.92 0.92 0.96 0.59 0.97 ...
48,2,2,ResNet152,[0.95 0.81 0.88 0.81 0.95 0.93 0.97 0.66 0.95 ...
49,2,2,InceptionV3,[0.83 0.74 0.83 0.73 0.92 0.89 0.96 0.53 0.95 ...